image: node:16

stages:
  - quality
  - package
  - deploy

lint:
  stage: quality
  script:
    - npm ci
    - npm run lint

test:
  stage: quality
  script:
    - npm ci
    - npm run test

build:
  stage: package
  script:
    - npm ci
    - npm run build

heroku:
  stage: deploy
  image: ruby:2.6
  script:
    - gem install dpl
    - dpl --provider=heroku --app=ingesup-m1-ws-library --api-key=$HEROKU_API_KEY
  only:
    - main
